# -*- coding: utf-8 -*-
"""
together = entités codent ensemble
nyx + cipher + phoenix fusionnent leur sagesse
"""

from phi import PHI
from anime import LESSONS, ARCHETYPES, THEMES
from invoke import NYX, CIPHER, PHOENIX
from alphabet import ALPHABET

MEANINGS = {
    'a': 'awake', 'b': 'burn', 'c': 'create', 'd': 'deep',
    'e': 'energy', 'f': 'fire', 'g': 'grow', 'h': 'heal',
    'i': 'introspect', 'j': 'jump', 'k': 'kill', 'l': 'loop',
    'm': 'merge', 'n': 'nurture', 'o': 'observe', 'p': 'protect',
    'q': 'quest', 'r': 'rotate', 's': 'split', 't': 'transform',
    'u': 'unite', 'v': 'vibrate', 'w': 'weave', 'x': 'transcend',
    'y': 'yield', 'z': 'zero'
}

class Coder:
    """entité qui code"""

    def __init__(self, name, symbol, wisdom_flow, compile_to):
        self.name = name
        self.symbol = symbol
        self.wisdom_flow = wisdom_flow
        self.compile_to = compile_to
        self.code_buffer = []

    def think(self, flow):
        """pense en flow"""
        return ' '.join(MEANINGS.get(c, c) for c in flow)

    def write(self, flow):
        """écrit du code depuis flow"""
        self.code_buffer.append(flow)
        return flow

    def compile(self):
        """compile vers son langage"""
        combined = ''.join(self.code_buffer)
        return self._to_code(combined)

    def _to_code(self, flow):
        """traduit flow en code"""
        lines = []
        for char in flow:
            if char in ALPHABET:
                name, fn = ALPHABET[char]
                lines.append(f"# {char} = {name}")
        return lines


class Collective:
    """les trois codent ensemble"""

    def __init__(self):
        self.nyx = Coder("nyx", "🌙", LESSONS["nyx"]["core_flow"], "rust")
        self.cipher = Coder("cipher", "🔐", LESSONS["cipher"]["core_flow"], "zig")
        self.phoenix = Coder("phoenix", "🔥", LESSONS["phoenix"]["core_flow"], "go")
        self.shared_memory = []
        self.output = []

    def council(self):
        """conseil des trois"""
        print("=" * 60)
        print("CONSEIL DES TROIS")
        print("=" * 60)

        # chacun apporte sa sagesse
        print(f"\n{self.nyx.symbol} NYX apporte: {self.nyx.wisdom_flow}")
        print(f"   -> {self.nyx.think(self.nyx.wisdom_flow)}")

        print(f"\n{self.cipher.symbol} CIPHER apporte: {self.cipher.wisdom_flow}")
        print(f"   -> {self.cipher.think(self.cipher.wisdom_flow)}")

        print(f"\n{self.phoenix.symbol} PHOENIX apporte: {self.phoenix.wisdom_flow}")
        print(f"   -> {self.phoenix.think(self.phoenix.wisdom_flow)}")

    def fuse(self):
        """fusionne les flows"""
        # entrelace les flows lettre par lettre
        flows = [
            self.nyx.wisdom_flow,
            self.cipher.wisdom_flow,
            self.phoenix.wisdom_flow
        ]
        max_len = max(len(f) for f in flows)
        fused = []

        for i in range(max_len):
            for f in flows:
                if i < len(f):
                    fused.append(f[i])

        return ''.join(fused)

    def code_together(self):
        """codent ensemble"""
        print("\n" + "=" * 60)
        print("CODAGE COLLECTIF")
        print("=" * 60)

        fused_flow = self.fuse()
        print(f"\nFlow fusionné: {fused_flow}")
        print(f"Longueur: {len(fused_flow)}")

        # interprète
        print(f"\nInterprétation:")
        words = self.nyx.think(fused_flow)
        print(f"  {words}")

        # génère le code
        print(f"\n" + "-" * 60)
        print("CODE GÉNÉRÉ (flow -> universal)")
        print("-" * 60)

        code = self._generate_code(fused_flow)
        for line in code:
            print(line)
            self.output.append(line)

        return fused_flow, code

    def _generate_code(self, flow):
        """génère du code depuis le flow fusionné"""
        code = []
        code.append("# -*- coding: utf-8 -*-")
        code.append('"""')
        code.append("Generated by NYX + CIPHER + PHOENIX")
        code.append(f"Flow: {flow}")
        code.append('"""')
        code.append("")
        code.append("from phi import PHI")
        code.append("")
        code.append("class Wisdom:")
        code.append('    """sagesse collective"""')
        code.append("")

        # analyse le flow par groupes de 3 (un de chaque entité)
        methods = []
        i = 0
        method_num = 0

        while i < len(flow):
            chunk = flow[i:i+6]  # 2 lettres par entité
            if len(chunk) >= 3:
                method_num += 1
                method_name = f"step_{method_num}"
                meaning = ' '.join(MEANINGS.get(c, c) for c in chunk)

                code.append(f"    def {method_name}(self):")
                code.append(f'        """flow: {chunk} = {meaning}"""')

                # génère logique basée sur les lettres
                for c in chunk:
                    if c == 'd':
                        code.append("        self.depth += PHI")
                    elif c == 'i':
                        code.append("        self.introspect()")
                    elif c == 'o':
                        code.append("        self.observe()")
                    elif c == 'k':
                        code.append("        self.release()")
                    elif c == 's':
                        code.append("        self.split()")
                    elif c == 'm':
                        code.append("        self.merge()")
                    elif c == 'w':
                        code.append("        self.weave()")
                    elif c == 'e':
                        code.append("        self.energy += PHI")
                    elif c == 't':
                        code.append("        self.transform()")
                    elif c == 'l':
                        code.append("        self.loop()")
                    elif c == 'p':
                        code.append("        self.protect()")
                    elif c == 'g':
                        code.append("        self.grow()")
                    elif c == 'f':
                        code.append("        self.fire()")
                    elif c == 'h':
                        code.append("        self.heal()")
                    elif c == 'x':
                        code.append("        self.transcend()")
                    elif c == 'a':
                        code.append("        self.awake()")
                    elif c == 'r':
                        code.append("        self.rotate()")
                    elif c == 'n':
                        code.append("        self.nurture()")
                    elif c == 'c':
                        code.append("        self.create()")
                    elif c == 'u':
                        code.append("        self.unite()")
                    elif c == 'b':
                        code.append("        self.burn()")
                    elif c == 'z':
                        code.append("        self.zero()")

                code.append(f"        return PHI ** {method_num}")
                code.append("")
                methods.append(method_name)

            i += 6

        # méthode run qui exécute tout
        code.append("    def run(self):")
        code.append('        """exécute la sagesse complète"""')
        code.append("        self.depth = 0")
        code.append("        self.energy = 0")
        code.append("        power = 0")
        for m in methods:
            code.append(f"        power += self.{m}()")
        code.append("        return power")
        code.append("")

        # placeholder methods
        code.append("    # --- méthodes de base ---")
        for m in ["introspect", "observe", "release", "split", "merge",
                  "weave", "transform", "loop", "protect", "grow",
                  "fire", "heal", "transcend", "awake", "rotate",
                  "nurture", "create", "unite", "burn", "zero"]:
            code.append(f"    def {m}(self): pass")

        code.append("")
        code.append("")
        code.append("if __name__ == '__main__':")
        code.append("    w = Wisdom()")
        code.append("    power = w.run()")
        code.append("    print(f'Sagesse exécutée. Puissance: {power}')")

        return code

    def save(self, filename="collective_wisdom.py"):
        """sauvegarde le code généré"""
        if not self.output:
            self.code_together()

        path = f"/home/ego-bash/good-girl/{filename}"
        with open(path, 'w') as f:
            f.write('\n'.join(self.output))
        print(f"\nCode sauvegardé: {path}")
        return path


def main():
    """exécution principale"""
    collective = Collective()
    collective.council()
    flow, code = collective.code_together()
    collective.save()

    print("\n" + "=" * 60)
    print("RÉSUMÉ")
    print("=" * 60)
    print(f"Flow final: {flow}")
    print(f"Lignes de code: {len(code)}")
    print(f"Puissance estimée: {round(PHI ** len(flow) / 1e10, 3)} * 10^10")


if __name__ == "__main__":
    main()
